#!/usr/bin/env bash
# =============================================================================
# vkQuake Dedicated Server - Entrypoint Script
# All server settings are controlled via environment variables.
# See Dockerfile for full list of variables and their defaults.
# =============================================================================
set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}=== vkQuake Server Starting ===${NC}"

# -----------------------------------------------------------------------------
# Validate game files
# -----------------------------------------------------------------------------
if [ ! -f "/quake/game/id1/pak0.pak" ]; then
    echo -e "${RED}ERROR: pak0.pak not found in /quake/game/id1/${NC}"
    echo -e "${YELLOW}Mount your Quake game files to /quake/game${NC}"
    exit 1
fi

# -----------------------------------------------------------------------------
# Create runtime directories
# -----------------------------------------------------------------------------
mkdir -p /quake/config /quake/logs

# -----------------------------------------------------------------------------
# Generate server.cfg
# Applied after Frogbot config — our values always win
# -----------------------------------------------------------------------------
create_server_config() {
    local config_file="/quake/config/server.cfg"

    cat > "$config_file" << EOF
// vkQuake Server Configuration
// Auto-generated by entrypoint.sh — do not edit manually
// Override any Frogbot defaults with values from environment variables

// Server identity
hostname "${QUAKE_SERVER_NAME}"
maxplayers ${QUAKE_MAX_PLAYERS}

// Game mode (only one of deathmatch/coop should be 1)
deathmatch ${QUAKE_DEATHMATCH}
coop ${QUAKE_COOP}
teamplay ${QUAKE_TEAMPLAY}

// Skill: standard Quake scale 0-3 (monsters in coop only, ignored by Frogbot)
skill ${QUAKE_SKILL}

// Match settings
fraglimit ${QUAKE_FRAGLIMIT}
timelimit ${QUAKE_TIMELIMIT}

// Bot skill: Frogbot scale 0-20 (0=Easiest, 5=Default, 10=Challenging, 20=Inhuman)
// d_skill is vkQuake/Frogbot's cvar for bot difficulty, overrides Frogbot's own config
set d_skill ${QUAKE_BOT_SKILL}

// Server behavior
pausable 0
sv_aim 1
sv_maxspeed 320
sv_friction 4
sv_edgefriction 2
sv_gravity 800
EOF

    # Only write rcon_password if set
    if [ -n "$QUAKE_ADMIN_PASSWORD" ]; then
        echo "rcon_password \"${QUAKE_ADMIN_PASSWORD}\"" >> "$config_file"
    fi

    # Add bots at startup if enabled
    if [ "$QUAKE_ENABLE_BOTS" = "1" ]; then
        echo "" >> "$config_file"
        echo "// Add bots after map loads" >> "$config_file"
        for i in $(seq 1 "$QUAKE_BOT_COUNT"); do
            echo "addbot" >> "$config_file"
        done
    fi

    echo -e "${GREEN}Server config written to $config_file${NC}"
}

# -----------------------------------------------------------------------------
# Build command line arguments
# -----------------------------------------------------------------------------
build_args() {
    local args=()

    # Dedicated server mode
    args+=("-dedicated" "$QUAKE_MAX_PLAYERS")
    args+=("-port" "$QUAKE_PORT")
    args+=("-basedir" "/quake/game")

    # Load Frogbot mod if bots are enabled
    if [ "$QUAKE_ENABLE_BOTS" = "1" ]; then
        if [ -d "/quake/game/frogbot" ] && [ -f "/quake/game/frogbot/progs.dat" ]; then
            args+=("-game" "frogbot")
            # Frogbot recommended zone size
            args+=("-zone" "1024")
            echo -e "${GREEN}Frogbot mod enabled${NC}"
        else
            echo -e "${YELLOW}WARNING: Frogbot files not found, starting without bots${NC}"
        fi
    fi

    # Memory
    args+=("-mem" "64")

    # Console log
    if [ "$QUAKE_CONDEBUG" = "1" ]; then
        args+=("-condebug")
    fi

    # Game mode cvars (set via + commands to override any config)
    args+=("+deathmatch"  "$QUAKE_DEATHMATCH")
    args+=("+coop"        "$QUAKE_COOP")
    args+=("+teamplay"    "$QUAKE_TEAMPLAY")
    args+=("+skill"       "$QUAKE_SKILL")
    args+=("+fraglimit"   "$QUAKE_FRAGLIMIT")
    args+=("+timelimit"   "$QUAKE_TIMELIMIT")
    args+=("+hostname"    "\"$QUAKE_SERVER_NAME\"")
    args+=("+maxplayers"  "$QUAKE_MAX_PLAYERS")
    args+=("+set d_skill" "$QUAKE_BOT_SKILL")

    # Admin password
    if [ -n "$QUAKE_ADMIN_PASSWORD" ]; then
        args+=("+rcon_password" "\"$QUAKE_ADMIN_PASSWORD\"")
    fi

    # Execute our server config (overrides Frogbot defaults)
    args+=("+exec" "../../config/server.cfg")

    # Starting map
    args+=("+map" "$QUAKE_MAP")

    printf '%s\n' "${args[@]}"
}

# -----------------------------------------------------------------------------
# Graceful shutdown handler
# -----------------------------------------------------------------------------
cleanup() {
    echo -e "\n${YELLOW}Shutting down vkQuake server...${NC}"
    if [ -n "${SERVER_PID:-}" ]; then
        kill -TERM "$SERVER_PID" 2>/dev/null || true
        wait "$SERVER_PID" 2>/dev/null || true
    fi
    echo -e "${GREEN}Server stopped cleanly${NC}"
    exit 0
}
trap cleanup SIGTERM SIGINT

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
main() {
    echo -e "${GREEN}--- Configuration ---${NC}"
    echo -e "Server Name : ${YELLOW}$QUAKE_SERVER_NAME${NC}"
    echo -e "Max Players : ${YELLOW}$QUAKE_MAX_PLAYERS${NC}"
    echo -e "Port        : ${YELLOW}$QUAKE_PORT${NC}"
    echo -e "Game Mode   : ${YELLOW}DM:$QUAKE_DEATHMATCH  COOP:$QUAKE_COOP  TEAM:$QUAKE_TEAMPLAY${NC}"
    echo -e "Skill       : ${YELLOW}$QUAKE_SKILL (Quake 0-3, coop/monsters only)${NC}"
    echo -e "Starting Map: ${YELLOW}$QUAKE_MAP${NC}"
    echo -e "Bots        : ${YELLOW}${QUAKE_ENABLE_BOTS} (count: $QUAKE_BOT_COUNT, skill: $QUAKE_BOT_SKILL/20)${NC}"
    echo -e "${GREEN}---------------------${NC}"

    create_server_config

    # Build args into an array safely (one arg per line)
    mapfile -t CMD_ARGS < <(build_args)

    echo -e "${GREEN}Starting server...${NC}"

    # Change to logs directory so qconsole.log lands there
    cd /quake/logs

    /quake/bin/vkquake "${CMD_ARGS[@]}" &
    SERVER_PID=$!

    echo -e "${GREEN}Server PID: $SERVER_PID${NC}"
    echo -e "${GREEN}Connect at: <your-ip>:$QUAKE_PORT${NC}"

    wait "$SERVER_PID"
}

main "$@"
