#!/usr/bin/env bash
# =============================================================================
# vkQuake Dedicated Server - Entrypoint Script
#
# All server settings are controlled via environment variables.
# See docker-compose.yml for the full list of variables and their defaults.
#
# Execution order (important for understanding overrides):
#   1. Frogbot autoexec.cfg runs → loads frogbot-quake.cfg (sets d_skill 5)
#   2. Our server.cfg runs → overrides hostname, maxplayers, fraglimit, etc.
#   3. +set d_skill on command line → overrides Frogbot's skill AFTER map loads
#   4. +addbot commands → bots spawn with correct skill
# =============================================================================
set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${GREEN}=== vkQuake Server Starting ===${NC}"

# -----------------------------------------------------------------------------
# Validate required game files
# -----------------------------------------------------------------------------
if [ ! -f "/quake/game/id1/pak0.pak" ]; then
    echo -e "${RED}ERROR: pak0.pak not found in /quake/game/id1/${NC}"
    echo -e "${YELLOW}Please mount your Quake game files to /quake/game/id1${NC}"
    exit 1
fi

# -----------------------------------------------------------------------------
# Create runtime directories
# -----------------------------------------------------------------------------
mkdir -p /quake/config /quake/logs

# -----------------------------------------------------------------------------
# Generate server.cfg
# This file is executed after Frogbot's autoexec.cfg, so our values win
# for everything EXCEPT d_skill — that is handled via command line args
# after +map to ensure it overrides Frogbot's post-map skill reset
# -----------------------------------------------------------------------------
create_server_config() {
    local config_file="/quake/config/server.cfg"

    cat > "$config_file" << EOF
// =============================================================================
// vkQuake Server Configuration
// Auto-generated by entrypoint.sh — do not edit manually
// Change settings via environment variables in docker-compose.yml
// =============================================================================

// --- Server identity ---
hostname "${QUAKE_SERVER_NAME}"
maxplayers ${QUAKE_MAX_PLAYERS}

// --- Game mode ---
// Only one of deathmatch/coop should be 1 at a time
deathmatch ${QUAKE_DEATHMATCH}
coop ${QUAKE_COOP}
teamplay ${QUAKE_TEAMPLAY}

// --- Skill: standard Quake scale 0-3 ---
// 0=Easy  1=Normal  2=Hard  3=Nightmare
// Only affects monsters in coop mode — ignored by Frogbot
skill ${QUAKE_SKILL}

// --- Match settings ---
fraglimit ${QUAKE_FRAGLIMIT}
timelimit ${QUAKE_TIMELIMIT}

// --- Server physics ---
sv_maxspeed ${QUAKE_MAX_SPEED}
sv_friction ${QUAKE_FRICTION}
sv_gravity ${QUAKE_GRAVITY}
sv_aim ${QUAKE_AIM}
pausable ${QUAKE_PAUSABLE}

// --- Map rotation ---
// Uses Frogbot's fb_nm alias system for NetQuake engines
// QUAKE_MAP_ROTATION is a comma-separated list of maps
// Example: start,e1m1,e1m2,e1m3
EOF

    # Generate map rotation aliases if enabled
    if [ "${QUAKE_ROTATION_MODE}" = "1" ] && [ -n "${QUAKE_MAP_ROTATION}" ]; then
        echo "" >> "$config_file"
        echo "// Auto-generated map rotation" >> "$config_file"

        # Split comma-separated map list into array
        IFS=',' read -ra MAPS <<< "${QUAKE_MAP_ROTATION}"
        local count=${#MAPS[@]}

        for (( i=0; i<count; i++ )); do
            current="${MAPS[$i]// /}"  # trim spaces
            next="${MAPS[$(( (i+1) % count ))]// /}"  # wrap around
            echo "alias nm_${current} \"cmd fb_nm ${next}\"" >> "$config_file"
        done

        echo -e "${GREEN}Map rotation configured: ${QUAKE_MAP_ROTATION}${NC}"
    fi

    # Admin password — only written if set, never empty
    if [ -n "${QUAKE_ADMIN_PASSWORD}" ]; then
        echo "" >> "$config_file"
        echo "rcon_password \"${QUAKE_ADMIN_PASSWORD}\"" >> "$config_file"
    fi

    echo -e "${GREEN}Server config written to $config_file${NC}"
}

# -----------------------------------------------------------------------------
# Build command line arguments
# -----------------------------------------------------------------------------
build_args() {
    local args=()

    # --- Core server settings ---
    args+=("-dedicated" "${QUAKE_MAX_PLAYERS}")
    args+=("-port" "${QUAKE_PORT}")
    args+=("-basedir" "/quake/game")
    args+=("-mem" "${QUAKE_MEMORY}")

    # --- Mod loading ---
    # If bots enabled and Frogbot exists, load frogbot mod
    # If QUAKE_MOD is set to something else, load that instead
    # If neither, run vanilla
    if [ "${QUAKE_ENABLE_BOTS}" = "1" ] && \
       [ -d "/quake/game/frogbot" ] && \
       [ -f "/quake/game/frogbot/progs.dat" ] && \
       [ -z "${QUAKE_MOD}" ]; then
        args+=("-game" "frogbot")
        args+=("-zone" "1024")
        echo -e "${GREEN}Frogbot mod loaded${NC}"
    elif [ -n "${QUAKE_MOD}" ] && [ -d "/quake/game/${QUAKE_MOD}" ]; then
        args+=("-game" "${QUAKE_MOD}")
        echo -e "${GREEN}Mod loaded: ${QUAKE_MOD}${NC}"
    else
        echo -e "${YELLOW}Running vanilla (no mod)${NC}"
    fi

    # --- Console debug log ---
    if [ "${QUAKE_CONDEBUG}" = "1" ]; then
        args+=("-condebug")
    fi

    # --- Game mode cvars ---
    # Set via + commands so they override any config file values
    args+=("+deathmatch"  "${QUAKE_DEATHMATCH}")
    args+=("+coop"        "${QUAKE_COOP}")
    args+=("+teamplay"    "${QUAKE_TEAMPLAY}")
    args+=("+skill"       "${QUAKE_SKILL}")
    args+=("+fraglimit"   "${QUAKE_FRAGLIMIT}")
    args+=("+timelimit"   "${QUAKE_TIMELIMIT}")
    args+=("+hostname"    "\"${QUAKE_SERVER_NAME}\"")
    args+=("+maxplayers"  "${QUAKE_MAX_PLAYERS}")

    # --- Admin password ---
    if [ -n "${QUAKE_ADMIN_PASSWORD}" ]; then
        args+=("+rcon_password" "\"${QUAKE_ADMIN_PASSWORD}\"")
    fi

    # --- Execute our server config ---
    # Runs after Frogbot's autoexec.cfg, overrides its settings
    args+=("+exec" "../../config/server.cfg")

    # --- Load starting map ---
    args+=("+map" "${QUAKE_MAP}")

    # --- Bot skill ---
    # MUST be set AFTER +map because Frogbot resets d_skill on map load
    # This is why it's here and not in server.cfg
    # Scale: 0=Easiest  5=Default  10=Challenging  20=Inhuman
    if [ "${QUAKE_ENABLE_BOTS}" = "1" ]; then
        args+=("+set d_skill" "${QUAKE_BOT_SKILL}")
    fi

    # --- Add bots after map loads ---
    # addbot commands execute sequentially after +map
    if [ "${QUAKE_ENABLE_BOTS}" = "1" ] && \
       [ -d "/quake/game/frogbot" ] && \
       [ -f "/quake/game/frogbot/progs.dat" ]; then
        for i in $(seq 1 "${QUAKE_BOT_COUNT}"); do
            args+=("+addbot")
        done
        echo -e "${GREEN}Will spawn ${QUAKE_BOT_COUNT} bot(s) at skill ${QUAKE_BOT_SKILL}/20${NC}"
    fi

    printf '%s\n' "${args[@]}"
}

# -----------------------------------------------------------------------------
# Graceful shutdown handler
# -----------------------------------------------------------------------------
cleanup() {
    echo -e "\n${YELLOW}Shutting down vkQuake server...${NC}"
    if [ -n "${SERVER_PID:-}" ]; then
        kill -TERM "${SERVER_PID}" 2>/dev/null || true
        wait "${SERVER_PID}" 2>/dev/null || true
    fi
    echo -e "${GREEN}Server stopped cleanly${NC}"
    exit 0
}
trap cleanup SIGTERM SIGINT

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
main() {
    echo -e "${CYAN}--- Server Configuration ---${NC}"
    echo -e "Server Name  : ${YELLOW}${QUAKE_SERVER_NAME}${NC}"
    echo -e "Max Players  : ${YELLOW}${QUAKE_MAX_PLAYERS}${NC}"
    echo -e "Port         : ${YELLOW}${QUAKE_PORT}${NC}"
    echo -e "Game Mode    : ${YELLOW}DM:${QUAKE_DEATHMATCH}  COOP:${QUAKE_COOP}  TEAM:${QUAKE_TEAMPLAY}${NC}"
    echo -e "Skill        : ${YELLOW}${QUAKE_SKILL}/3 (Quake scale, coop/monsters only)${NC}"
    echo -e "Frag Limit   : ${YELLOW}${QUAKE_FRAGLIMIT}${NC}"
    echo -e "Time Limit   : ${YELLOW}${QUAKE_TIMELIMIT} min${NC}"
    echo -e "Starting Map : ${YELLOW}${QUAKE_MAP}${NC}"
    echo -e "Map Rotation : ${YELLOW}${QUAKE_ROTATION_MODE} (${QUAKE_MAP_ROTATION})${NC}"
    echo -e "Mod          : ${YELLOW}${QUAKE_MOD:-frogbot (built-in)}${NC}"
    echo -e "Bots         : ${YELLOW}${QUAKE_ENABLE_BOTS} — count: ${QUAKE_BOT_COUNT}, skill: ${QUAKE_BOT_SKILL}/20${NC}"
    echo -e "Memory       : ${YELLOW}${QUAKE_MEMORY}MB${NC}"
    echo -e "Gravity      : ${YELLOW}${QUAKE_GRAVITY}${NC}"
    echo -e "Max Speed    : ${YELLOW}${QUAKE_MAX_SPEED}${NC}"
    echo -e "${CYAN}----------------------------${NC}"

    create_server_config

    # Build args safely into array (one arg per line)
    mapfile -t CMD_ARGS < <(build_args)

    echo -e "${GREEN}Starting vkQuake server...${NC}"

    # Change to logs directory so qconsole.log lands there
    cd /quake/logs

    /quake/bin/vkquake "${CMD_ARGS[@]}" &
    SERVER_PID=$!

    echo -e "${GREEN}Server PID  : ${SERVER_PID}${NC}"
    echo -e "${GREEN}Connect at  : <your-ip>:${QUAKE_PORT}${NC}"
    echo -e "${GREEN}Logs at     : /quake/logs/qconsole.log${NC}"

    wait "${SERVER_PID}"
}

main "$@"
